### ISSUE TITLE
[Feature] Textures invalidated in council don't update the original submission

### ISSUE THREAD

**Issue by Faithful-Pack** [Faithful-Resource-Pack/CompliBot-Submissions#11]
*Issue originally created by `evorp` on Discord*

### Is your feature request related to a problem?

read the title

### Describe the feature you'd like

If a texture is invalidated in a council channel, use the "original post" link to find the original message and update that too

### Notes

should be easy enough with regex and stuff (also first real test of the feedback system wooooo)

**Comment by 3vorp** [comment]
oh yeah also this is just a note for me:

for the love of god please rename invalidSubmission to something less ambiguous so that people don't confuse it as an invalidation rather than a submission cancellation (cancelSubmission would honestly be a decent name)
