### ISSUE TITLE
[Bug] Textures can get skipped in voting if there's more than 100

### ISSUE THREAD

**Issue by Faithful-Pack** [Faithful-Resource-Pack/CompliBot-Submissions#12]
*Issue originally created by `evorp` on Discord*

### What happened?

For optimization purposes, the bot caps the amount of scanned submissions at 100 (this can technically be increased to an arbitrary number but it will lag the bot substantially more and is overall not worth it). However, this can cause a lot of problems if more than 100 submissions are posted in a day, such as the recent events with the GUI.

Would probably be best solved by passing in a filter callback into the function so it just needs to scan as many items as needed and returns the results, rather than scanning 100 regardless of if it matches any criteria or not.

### To reproduce

- Submit more than 100 textures
- The bot ignores anything past the 100th submission.

### Notes

*No response*

**Comment by 3vorp** [comment]
seems to have been fixed with cfa6a3f2ca440ac4d67ea20cb8c8b6a240b08c56, tentatively closing for now
